### ISSUE TITLE
Not working for file uploads

### ISSUE THREAD

**Issue by Lc5** [webmozart/standalone-forms#1]
Hello,
I've got file upload field in my form. The data is correctly sent using POST, however, when using the following code, the UploadedFile object is not created, when calling "$form['attachment']->getData():"

$builder->add('attachment', 'file');

if ($form->isValid()) {
        $someNewFilename = ...

```
    $form['attachment']->getData()->move($dir, $someNewFilename);

    // ...
}
```

Calling $form->getData() returns, among others, an array of fields with user file names.
I suppose the problem could be in FileBag not being called at all.

**Comment by webmozart** [comment]
For automatic handling of file uploads, you need to also install `symfony/http-foundation` and enable HttpFoundationExtension.

``` php
use Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationExtension;

$formFactory = Forms::createFormFactoryBuilder()
    ->addExtension(new CsrfExtension($csrfProvider))
    ->addExtension(new ValidatorExtension($validator))
    ->addExtension(new HttpFoundationExtension())
    ->getFormFactory();
```

**Comment by Lc5** [comment]
Thanks for explanation!
