### ISSUE TITLE
Using standalone-forms without Twig

### ISSUE THREAD

**Issue by jasonbouffard** [webmozart/standalone-forms#2]
Do you think it would be worth it to show an implementation of Symfony Forms with the bare minimum dependencies, like without Twig?

**Comment by jasonbouffard** [comment]
Well. I see you used to have it using PHP.

https://github.com/bschussek/standalone-forms/commit/8ba8bd1d22a08a43693e58a74708ca7f7e7eb759

**Comment by webmozart** [comment]
You either need to use Twig or PHP, or any other templating system. So this in fact are the minimum requirements. You can find both alternatives showcased in branches of this repository.
