### ISSUE TITLE
Translation doesn't work in version >2.1

### ISSUE THREAD

**Issue by nadrshin** [webmozart/standalone-forms#7]
code:
$translator = new Translator('ru');
$translator->addLoader('xlf', new XliffFileLoader());
$translator->addResource('xlf', VENDOR_FORM_DIR . '/Resources/translations/validators.ru.xlf', 'ru', 'validators');
$translator->addResource('xlf', VENDOR_VALIDATOR_DIR . '/Resources/translations/validators.ru.xlf', 'ru', 'validators');

version 2.1:
result: OK

version >2.1:
result: FAIL

What to do?

**Comment by berny46** [comment]
I'm on Symfony 2.6, having the same problem.
I figured out, that in this part (I'm using twig), the last three lines don't have any effect. You can just leave them away.

```
// Set up the Translation component
$translator = new Translator('en');
$translator->addLoader('xlf', new XliffFileLoader());
$translator->addResource('xlf', VENDOR_FORM_DIR . '/Resources/translations/validators.en.xlf', 'en', 'validators');
$translator->addResource('xlf', VENDOR_VALIDATOR_DIR . '/Resources/translations/validators.en.xlf', 'en', 'validators');
```

Any help would be appreciated.
Thanks,
Chris

**Comment by ldath** [comment]
Now this example is upgraded to 2.7 of the Symfony Forms library. This problem is solved.

**Comment by webmozart** [comment]
Thanks @ldath :) I guess this can be closed now.
